dataset_name: i5O
devices: ['cuda:0']
train_split: ['validation']
val_split: ['test']
dataset: {
  json_file: /data/fady/aar/video_features/annotations/i5Oannotations_r21d_rgb.json,
  feat_folder: /data/r46rahma/data/i5O/i5OData/video_features/r21d/r2plus1d_18_16_kinetics/stack_size16step_size4extraction_fpsNone_flat/,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 20, # i5O has 20 classes
  input_dim: 512,
  feat_stride: 4,
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 19,
}
opt: {
  learning_rate: 0.0001,
  epochs: 30,
  weight_decay: 0.05,
}
loader: {
  batch_size: 32,
  num_workers: 8, 
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # Test commit
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: ./ckpt/
